# Site
site_name: SupImDos
site_description: My Personal Website
site_url: https://supimdos.com
site_author: SupImDos

# Copyright
copyright: Copyright &copy; 2022 Hayden Richards

# Repository
repo_name: SupImDos/website
repo_url: https://github.com/SupImDos/website
edit_uri: ""

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Showcase: showcase.md

# Theme
theme:
  name: material
  icon:
    logo: material/home
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SupImDos
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hayden-peter-richards/
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:supimdos@gmail.com
      name: Email
    - icon: fontawesome/solid/file-contract
      link: /assets/documents/resume.pdf
      name: Resume

# Markdown Extensions
markdown_extensions:
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search
